# Generated by Django 3.1 on 2020-09-08 21:29

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='album',
            field=models.IntegerField(default=0, verbose_name=main_app.models.Album),
        ),
    ]
