# Generated by Django 3.1 on 2020-09-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200908_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='rating',
            field=models.IntegerField(blank=True, choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5]], default=5, null=True),
        ),
    ]
