# Generated by Django 3.1 on 2020-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200908_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='art',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
