# Generated by Django 3.1 on 2020-09-10 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_auto_20200909_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='art_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='artist',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.CreateModel(
            name='CollectionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3)),
                ('review', models.TextField(blank=True, null=True)),
                ('user_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ratings', to=settings.AUTH_USER_MODEL)),
                ('user_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_rated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
