# Generated by Django 3.1 on 2020-09-10 13:27

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200910_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrating',
            name='album',
            field=models.IntegerField(default=0, verbose_name=main_app.models.Album),
        ),
        migrations.AddField(
            model_name='collectionrating',
            name='art_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collectionrating',
            name='artist',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='collectionrating',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
