# Generated by Django 3.1 on 2020-09-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200910_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrating',
            name='user_collection',
        ),
    ]
