# Generated by Django 3.1 on 2020-09-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_collectionrating_user_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionrating',
            old_name='user_rating',
            new_name='user',
        ),
    ]
